package selenium;// Generated by Selenium IDE
// Test By Gianluca Ronzello
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class EuroInDollarsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void euroInDollars() {
    driver.get("https://www.convertworld.com/it/");
    driver.manage().window().setSize(new Dimension(660, 672));
    driver.findElement(By.name("amount")).click();
    driver.findElement(By.name("amount")).sendKeys("12");
    driver.findElement(By.id("from_currency")).click();
    {
      WebElement dropdown = driver.findElement(By.id("from_currency"));
      dropdown.findElement(By.xpath("//option[. = 'Euro (EUR)']")).click();
    }
    driver.findElement(By.id("to_currency")).click();
    {
      WebElement dropdown = driver.findElement(By.id("to_currency"));
      dropdown.findElement(By.xpath("//option[. = 'Dollaro (USD)']")).click();
    }
    assertThat(driver.findElement(By.cssSelector("#div_currency > b")).getText(), is("13,62 USD"));
  }
}
