package selenium;
// Generated by Selenium IDE (test by Lioi Alessandro)

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class InchtocmTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void inchtocm() {
        driver.get("https://www.unitconverters.net/length/inches-to-cm.htm");
        driver.manage().window().setSize(new Dimension(945, 1012));
        driver.findElement(By.id("ucfrom")).sendKeys("1");
        driver.findElement(By.cssSelector(".ucdcsubmit:nth-child(3)")).click();
        {
            WebElement element = driver.findElement(By.linkText("Power"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        {
            String value = driver.findElement(By.id("ucto")).getAttribute("value");
            assertThat(value, is("2.54"));
        }
    }
}
